//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.ServiceModel.Description;
using System.Threading.Tasks;
using System.Xml;
using Newtonsoft.Json.Linq;

namespace WarehouseReference
{
    [GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [ServiceContractAttribute(ConfigurationName="WarehouseReference.IEmulatorService")]
    public interface IEmulatorService
    {
        
        [OperationContractAttribute(Action="http://tempuri.org/IEmulatorService/PickItem", ReplyAction="http://tempuri.org/IEmulatorService/PickItemResponse")]
        Task<string> PickItemAsync(int trayId);
        
        [OperationContractAttribute(Action="http://tempuri.org/IEmulatorService/InsertItem", ReplyAction="http://tempuri.org/IEmulatorService/InsertItemResponse")]
        Task<string> InsertItemAsync(int trayId, string name);
        
        [OperationContractAttribute(Action="http://tempuri.org/IEmulatorService/GetInventory", ReplyAction="http://tempuri.org/IEmulatorService/GetInventoryResponse")]
        Task<string> GetInventoryAsync();
    }
    
    [GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IEmulatorServiceChannel : WarehouseReference.IEmulatorService, IClientChannel
    {
    }
    
    [DebuggerStepThroughAttribute()]
    [GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class EmulatorServiceClient : ClientBase<WarehouseReference.IEmulatorService>, WarehouseReference.IEmulatorService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(ServiceEndpoint serviceEndpoint, ClientCredentials clientCredentials);
        
        public EmulatorServiceClient() : 
                base(EmulatorServiceClient.GetDefaultBinding(), EmulatorServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IEmulatorService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmulatorServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(EmulatorServiceClient.GetBindingForEndpoint(endpointConfiguration), EmulatorServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmulatorServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EmulatorServiceClient.GetBindingForEndpoint(endpointConfiguration), new EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmulatorServiceClient(EndpointConfiguration endpointConfiguration, EndpointAddress remoteAddress) : 
                base(EmulatorServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmulatorServiceClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Task<string> PickItemAsync(int trayId)
        {
            return base.Channel.PickItemAsync(trayId);
        }
        
        public Task<string> InsertItemAsync(int trayId, string name)
        {
            return base.Channel.InsertItemAsync(trayId, name);
        }
        
        public Task<string> GetInventoryAsync()
        {
            return base.Channel.GetInventoryAsync();
        }
        
        public virtual Task OpenAsync()
        {
            return Task.Factory.FromAsync(((ICommunicationObject)(this)).BeginOpen(null, null), new Action<IAsyncResult>(((ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual Task CloseAsync()
        {
            return Task.Factory.FromAsync(((ICommunicationObject)(this)).BeginClose(null, null), new Action<IAsyncResult>(((ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEmulatorService))
            {
                BasicHttpBinding result = new BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEmulatorService))
            {
                return new EndpointAddress("http://localhost:8081/Service.asmx");
            }
            throw new InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static Binding GetDefaultBinding()
        {
            return EmulatorServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IEmulatorService);
        }
        
        private static EndpointAddress GetDefaultEndpointAddress()
        {
            return EmulatorServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IEmulatorService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IEmulatorService,
        }
    }
}
